name: Build and Pack

on:
  workflow_call:
    inputs: 
      project-name:
        required: true
        type: string
      project-path:
        required: true
        type: string

jobs:
  build-function:
    outputs:
      artifact: ${{steps.zip.outputs.artifact}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        run: dotnet publish ${{inputs.project-path}}/${{inputs.project-name}}.csproj --output publish/${{inputs.project-name}}
      - name: zip
        run: |
          mkdir out
          export VERSION=1.0.${{github.run_number}}
          export ZIPFILE=${{inputs.project-name}}.$VERSION.zip
          echo "artifact=${{inputs.project-name}}.$VERSION.zip" >> "$GITHUB_OUTPUT"
          zip ./out/$ZIPFILE ./publish/${{inputs.project-name}}/*
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.zip.outputs.artifact}}
          path: out/${{steps.zip.outputs.artifact}}