# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bin
        path: |
          **/bin/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build
      uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: bin
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  deploy-lambda-one-test:
    needs: test
    environment: test
    uses: ./.github/workflows/lambda_deploy.yml
    secrets: inherit
    with:
      function-name: LambdaOne
      project-name: LambdaOne
      project-path: LambdaOne/src/LambdaOne