name: Deploy a Lambda

on:
  workflow_call:
    inputs: 
      function-name:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      target-environment:
        required: true
        type: string
  workflow_dispatch:
    inputs: 
      function-name:
        description: "Function name to be updated, independent of the environment"
        required: true
        type: string
      artifact-name:
        description: "Name of the github artifact to be deployed"
        required: true
        type: string
      target-environment:
        description: "Environment to be deployed to"
        required: true
        type: environment
      run-id:
        description: "Run number that generated the target artifact"
        required: true
        type: number

jobs:
  deploy-function:
    environment: ${{inputs.target-environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
          run-id: ${{inputs.run-id}}
      - name: deploy
        run: |
          aws lambda update-function-code --function-name ${{vars.ENV_PREFIX}}${{inputs.function-name}} --zip-file fileb://${{inputs.artifact-name}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-2'