name: Deploy a Lambda

on:
  workflow_call:
    inputs: 
      function-name:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      target-environment:
        required: true
        type: string

jobs:
  deploy-function:
    environment: ${{inputs.target-environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}
      - name: deploy
        run: |
          aws lambda update-function-code --function-name ${{vars.ENV_PREFIX}}${{inputs.function-name}} --zip-file fileb://${{inputs.artifact-name}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-2'